LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
 
LOCAL_MODULE := ???

LOCAL_SRC_FILES := \

LOCAL_C_INCLUDES := $(INCLUDES)

LOCAL_CFLAGS := $(L_CFLAGS)
LOCAL_LDLIBS += ???

LOCAL_STATIC_LIBRARIES := \
LOCAL_SHARED_LIBRARIES := \
 
include $(BUILD_EXECUTABLE)
