LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)
 
LOCAL_MODULE = ???

LOCAL_CFLAGS = $(L_CFLAGS)

LOCAL_SRC_FILES = ???

LOCAL_C_INCLUDES = $(INCLUDES)

LOCAL_SHARED_LIBRARIES := \

LOCAL_COPY_HEADERS_TO := \
LOCAL_COPY_HEADERS := \

LOCAL_MODULE_TAGS := ???
 
include $(BUILD_STATIC_LIBRARY)
