# This file was generated by extconf.rb
module CommandT
  module Metadata
    EXPECTED_RUBY_VERSION = "1.8.7"
    EXPECTED_RUBY_PATCHLEVEL = 352
    UNKNOWN = false
  end # module Metadata
end # module CommandT
